apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-vol
  labels:
    name: nginx-configmap-vol
spec:
  # volumes:
  #   - name: conifg
  #     configMap:
  #       name: fortune-config
  containers:
  - name: nginx-configmap-vol
    image: nginx:1.7.9
    # volumeMounts:
    #   - name:  conifg
    #     mountPath:  /etc/nginx/conf.d
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
