apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"env":"prod"},"name":"goapp-pod2","namespace":"default"},"spec":{"containers":[{"image":"dangtong/goapp","name":"goapp-container","ports":[{"containerPort":8080,"protocol":"TCP"}]}]}}
    maker: gyungmean
    team: olivenetwork
  creationTimestamp: "2025-01-09T02:51:36Z"
  labels:
    app: application
    env: prod
    tier: frontEnd
  name: goapp-pod2
  namespace: default
  resourceVersion: "22212"
  uid: 29520375-6dfc-42ba-ac3e-3c61289f14a7
spec:
  containers:
  - image: dangtong/goapp
    imagePullPolicy: Always
    name: goapp-container
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hpsb8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cwave-cluster-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hpsb8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-09T02:51:40Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-01-09T02:51:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-09T02:51:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-09T02:51:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-09T02:51:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f5c51c1d2ddba3691e1480769b71022e41cdfa249b98edb792aff96abeef995f
    image: docker.io/dangtong/goapp:latest
    imageID: docker.io/dangtong/goapp@sha256:905cee88a70a870696612033672b3adeb4e104640f4741d1d9a9774c06570687
    lastState: {}
    name: goapp-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-01-09T02:51:39Z"
  hostIP: 172.22.0.3
  hostIPs:
  - ip: 172.22.0.3
  phase: Running
  podIP: 10.110.2.4
  podIPs:
  - ip: 10.110.2.4
  qosClass: BestEffort
  startTime: "2025-01-09T02:51:36Z"
