apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: nodeapp-pod
  ports:
  - port: 80
    targetPort: 8080
