apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-01-09T02:31:06Z"
    labels:
      name: nginx-app
    name: nginx-app
    namespace: default
    resourceVersion: "17639"
    uid: b2a4eb9b-7e7c-4d21-b403-e580fb55fd4a
  spec:
    containers:
    - image: nginx:1.18.0
      imagePullPolicy: IfNotPresent
      name: nginx-app
      ports:
      - containerPort: 80
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 500m
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cw7vn
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: cwave-cluster-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-cw7vn
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:31:19Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:31:07Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:31:19Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:31:19Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:31:07Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://42e6983241cbae38acfa92f6709ca40d81b2098aa5c98c3b1f5f021f4d6dd5a9
      image: docker.io/library/nginx:1.18.0
      imageID: docker.io/library/nginx@sha256:e90ac5331fe095cea01b121a3627174b2e33e06e83720e9a934c7b8ccc9c55a0
      lastState: {}
      name: nginx-app
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-01-09T02:31:19Z"
    hostIP: 172.22.0.3
    hostIPs:
    - ip: 172.22.0.3
    phase: Running
    podIP: 10.110.2.3
    podIPs:
    - ip: 10.110.2.3
    qosClass: Guaranteed
    startTime: "2025-01-09T02:31:07Z"
kind: List
metadata:
  resourceVersion: ""
